#%RAML 1.0 NamedExample
value:
  - authorName: "sanjay chaudhary"
    title: "learn coding"
    bookedition: "4"
    published year: "2019"
    publisherName: "SDK publishers"
    booketype: "mp3"
    price: "189"
  - authorName: "rohit chaudhary"
    title: "learn DevOps"
    bookedition: "4"
    published year: "2019"
    publisherName: "SDK publishers"
    booketype: "pdf"
    price: "200"